name: Summary example

on:
  workflow_dispatch:

jobs:
  summary:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Write job summary
        run: cat wfc-summary-example.md >> "$GITHUB_STEP_SUMMARY"
